---
apiVersion: fluentd.fluent.io/v1alpha1
kind: ClusterInput
metadata:
  name: prometheus
  labels:
    input.fluentd.fluent.io/enabled: "true"
spec:
  inputs:
    - customPlugin:
        config: |
          <source>
            @type prometheus
            bind 0.0.0.0
            port 24231
            metrics_path /metrics
          </source>
          <source>
            @type prometheus_output_monitor
            interval 5
          </source>
