---
apiVersion: v1
kind: Service
metadata:
  name: fluentd-metrics
  namespace: system-observability
  labels:
    app.kubernetes.io/name: fluentd
spec:
  type: ClusterIP
  ports:
    - name: prometheus
      port: 24231
      targetPort: 24231
      protocol: TCP
  selector:
    app.kubernetes.io/name: fluentd
