apiVersion: kustomize.config.k8s.io/v1alpha1
kind: Component

# Log level filter: INFO
#
# Drops logs with severity below INFO (TRACE, DEBUG).
# This is the default log level for production environments.

resources:
  - clusterfilter.yaml
