apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: prometheus-community
  namespace: system-gitops
spec:
  interval: 10m
  timeout: 5m
  url: https://prometheus-community.github.io/helm-charts
