apiVersion: kustomize.config.k8s.io/v1alpha1
kind: Component
resources:
  - fluentbit-clusterfilter.yaml
configMapGenerator:
  - name: fluent-bit-service-name-config
    namespace: system-telemetry
    files:
      - service-name.lua
    options:
      disableNameSuffixHash: true
