---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: fluent-bit
  namespace: system-telemetry
  labels:
    app.kubernetes.io/name: fluent-bit
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: fluent-bit
  podTargetLabels:
    - app.kubernetes.io/name
    - app.kubernetes.io/instance
  endpoints:
    - port: metrics
      path: /api/v2/metrics/prometheus
      interval: 30s
      relabelings:
        # Add pod name label from __meta_kubernetes_pod_name
        - sourceLabels: [__meta_kubernetes_pod_name]
          targetLabel: pod
        # Add node name label from __meta_kubernetes_pod_node_name
        - sourceLabels: [__meta_kubernetes_pod_node_name]
          targetLabel: node
        # Add namespace label
        - sourceLabels: [__meta_kubernetes_namespace]
          targetLabel: namespace
