apiVersion: kustomize.config.k8s.io/v1alpha1
kind: Component

# Log level filter: ERROR
#
# Drops logs with severity below ERROR (TRACE, DEBUG, INFO, WARN).
# Use this for minimal logging.

resources:
  - clusterfilter.yaml
